spring:
  application:
    name: demo
  cloud:
    tencent:
      metadata:
        content:
          idc: bj
          env: dev
    polaris:
      address: grpc://127.0.0.1:28091
      namespace: default
#    loadbalancer:
#      cache:
#        caffeine:
#          spec: initialCapacity=500,expireAfterWrite=5s
#        enabled: true